//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace humeyrayıldız_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productinformation1
    {
        public int ID { get; set; }
        public string PRODUCTNAME { get; set; }
        public string BRAND { get; set; }
        public string STOCK { get; set; }
        public Nullable<decimal> BUYPRİCE { get; set; }
        public Nullable<decimal> SELLPRİCE { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<bool> PRODUCTCASE { get; set; }
    }
}
